version: '3'
services:
  postgre-text-search:
    build: .
    command: sh -c "cd ${GO_PROJECT_DIR}/app && realize start"
    volumes:
      - .:${GO_PROJECT_DIR}
    ports:
      - 9911:9911
    environment:
      - GO_WORK_DIR=${GO_PROJECT_DIR}/app